kind = "web"
previewPath = "/"
title = "MZAZI TECH INC"
version = "1.0.0"
id = "artifacts/mzazi-tech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19351

[services.development]
run = "pnpm --filter @workspace/mzazi-tech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mzazi-tech", "run", "build" ]
publicDir = "artifacts/mzazi-tech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19351"
BASE_PATH = "/"
